"use client";
import {useState} from 'react';
import {Trophy,Download} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import type {AiSeries} from '@/lib/table';
export function SeriesSetup({names,onNames,games,onGames,enabled,onEnabled,fast,onFast}:{names:string[];onNames:(v:string[])=>void;games:number;onGames:(v:number)=>void;enabled:boolean;onEnabled:(v:boolean)=>void;fast:boolean;onFast:(v:boolean)=>void}){
 return <div className="series-setup"><h3>AI players</h3>{names.map((name,i)=><label key={i}>AI {i+1}<input aria-label={`AI ${i+1} name`} maxLength={30} value={name} onChange={e=>onNames(names.map((n,j)=>j===i?e.target.value:n))}/></label>)}<label className="series-check"><input type="checkbox" checked={enabled} onChange={e=>onEnabled(e.target.checked)}/>Run consecutive AI games</label>{enabled&&<><label>Number of games<input aria-label="Number of AI games" type="number" min={1} max={100} value={games} onChange={e=>onGames(Number(e.target.value))}/></label><label className="series-check"><input type="checkbox" checked={fast} onChange={e=>onFast(e.target.checked)}/>Fast testing · skip presentation delays</label><p>Keep this server running. The same four decks are reshuffled each game. Results remain available until a new run or server restart.</p></>}</div>;
}
export function SeriesResults({series,host,busy,onStop}:{series:AiSeries;host:boolean;busy:boolean;onStop:()=>void}){
 const [open,setOpen]=useState(false);
 const download=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(series,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`ai-series-${series.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <><button className="series-score" onClick={()=>setOpen(true)}><Trophy size={17}/>AI series · {series.completed}/{series.total} · {series.running?'Running':'Results'}</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="series-results"><DialogTitle>AI series results</DialogTitle><DialogDescription>{series.completed} completed games · {series.draws} draws · {series.running?(series.stopRequested?'Stopping after this game':'Running'):series.stopped||'Complete'}. Win rates describe this series, not general deck strength.</DialogDescription><h3>By AI and deck</h3><table><thead><tr><th>AI</th><th>Deck</th><th>Wins</th><th>Games</th></tr></thead><tbody>{series.players.map(p=><tr key={p.seat}><td>{p.name} <small>#{p.seat+1}</small></td><td>{p.deck}</td><td>{p.wins}</td><td>{p.games}</td></tr>)}</tbody></table><h3>By deck</h3><table><thead><tr><th>Deck</th><th>Wins</th><th>Appearances</th><th>Win rate</th></tr></thead><tbody>{series.decks.map(d=><tr key={d.deck}><td>{d.deck}</td><td>{d.wins}</td><td>{d.games}</td><td>{d.games?(100*d.wins/d.games).toFixed(1):'0'}%</td></tr>)}</tbody></table><p className="small-note">A deck in two seats has two appearances per game. Interrupted or failed games do not count as wins.</p><details><summary>Individual game results</summary><ol>{series.results.map(r=><li key={r.game}>Game {r.game}: {r.draw?'Draw':r.winners.map(i=>series.players.find(p=>p.seat===i)?.name).join(', ')} · {r.turns} turns · {r.seconds}s</li>)}</ol></details><div className="prompt-buttons"><button onClick={download}><Download size={16}/>Export results</button>{host&&series.running&&<button disabled={busy||series.stopRequested} onClick={onStop}>{series.stopRequested?'Stopping after this game':'Stop after current game'}</button>}</div></DialogContent></Dialog></>;
}
