"use client";
import {useState} from 'react';
import {ArrowDown,ArrowUp,Check} from 'lucide-react';
import {CardArt} from './table-card';
import {Card,Decision} from '@/lib/table';
export default function DecisionPanel({decision:d,busy,onAnswer,onInspect}:{decision:Decision;busy:boolean;onAnswer:(body:Record<string,unknown>)=>void;onInspect:(c:Card)=>void}){
 const [selected,setSelected]=useState<number[]>([]),[value,setValue]=useState(String(d.min)),[values,setValues]=useState<number[]>(d.options.map(()=>d.min));
 const toggle=(id:number)=>{if(d.kind==='reveal')return;setSelected(old=>old.includes(id)?old.filter(i=>i!==id):d.max===1?[id]:old.length<d.max?[...old,id]:old)};
 const allocation=d.kind==='allocation',number=d.kind==='number',text=d.kind==='text',reveal=d.kind==='reveal',order=d.kind==='order',stack=d.kind==='stack';
 const valid=allocation?values.reduce((a,b)=>a+b,0)===d.max&&values.every(v=>Number.isInteger(v)&&v>=d.min):number?Number.isInteger(Number(value))&&Number(value)>=d.min&&Number(value)<=d.max:text?value.length<=500:reveal||selected.length>=(stack?Math.max(1,d.min):d.min)&&selected.length<=d.max;
 const answer=()=>onAnswer({decisionId:d.id,...(allocation?{values}:number?{value:Number(value)}:text?{value}:{selected})});
 const move=(i:number,by:number)=>setSelected(old=>{const next=[...old];[next[i],next[i+by]]=[next[i+by],next[i]];return next});
 return <section className={`decision-panel ${stack?'stack-decision':''}`}><div className="eyebrow">SUA DECISÃO</div><h3>{d.message}</h3>{!reveal&&!number&&!text&&!allocation&&<p>{stack?'Escolha o alvo na pilha e confirme.':<>Escolha {d.min===d.max?d.min:`de ${d.min} a ${d.max}`} {d.max===1?'opção':'opções'}.{order?' A ordem dos cliques define a ordem das cartas.':''}</>}</p>}{(number||text)&&<label>{number?`Valor entre ${d.min} e ${d.max}`:'Resposta'}<input autoFocus type={number?'number':'text'} value={value} min={d.min} max={d.max} maxLength={500} onChange={e=>setValue(e.target.value)}/></label>}<div className="decision-options">{d.options.map((o,i)=><div className="decision-row" key={o.id}><button className={`decision-option ${selected.includes(o.id)?'chosen':''}`} disabled={busy||reveal||allocation} onClick={()=>toggle(o.id)} onMouseEnter={()=>o.card&&onInspect(o.card)} onFocus={()=>o.card&&onInspect(o.card)}>{selected.includes(o.id)&&<span className="choice-number">{order?selected.indexOf(o.id)+1:<Check size={13}/>}</span>}{stack&&o.card&&<CardArt card={o.card}/>}<span>{o.label}</span></button>{o.card&&<button className="small-button" onClick={()=>o.card&&onInspect(o.card)} aria-label={'Ver '+o.label}>Ver</button>}{allocation&&<input aria-label={'Quantidade para '+o.label} type="number" min={d.min} max={d.max} value={values[i]} onChange={e=>setValues(old=>old.map((n,j)=>j===i?Number(e.target.value):n))}/>}</div>)}</div>{order&&selected.length>1&&<div className="chosen-order">{selected.map((id,i)=><div key={id}><span>{i+1}. {d.options.find(o=>o.id===id)?.label}</span><button aria-label="Subir" disabled={i===0} onClick={()=>move(i,-1)}><ArrowUp size={13}/></button><button aria-label="Descer" disabled={i===selected.length-1} onClick={()=>move(i,1)}><ArrowDown size={13}/></button></div>)}</div>}{allocation&&<p>Distribuído: {values.reduce((a,b)=>a+b,0)} / {d.max}</p>}<button className="primary" disabled={busy||!valid} onClick={answer}>{busy?'Enviando…':reveal?'Entendido':stack?'Confirmar alvo':'Confirmar escolha'}</button>{stack&&d.min===0&&<button className="cancel-target" disabled={busy} onClick={()=>onAnswer({decisionId:d.id,selected:[]})}>Cancelar escolha</button>}</section>
}
