"use client";
import {useState} from 'react';
import {Search,Check} from 'lucide-react';
import {CardArt} from './table-card';
import AiCoverage from './ai-coverage';
import type {Health} from '@/lib/table';
export default function DeckBrowser({decks,value,onChange}:{decks:Health['decks'];value:string;onChange:(id:string)=>void}){
 const [search,setSearch]=useState(''),[kind,setKind]=useState('all');
 const deck=decks.find(d=>d.id===value);
 return <div className="deck-browser"><section className="deck-catalog"><label className="deck-search"><Search size={16}/><input aria-label="Search decks" placeholder="Deck or commander…" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="deck-filters">{['all','original','adapted'].map(k=><button key={k} aria-pressed={kind===k} onClick={()=>setKind(k)}>{k==='all'?'All':k==='original'?'Originals':'AI adapted'}</button>)}</div><div className="deck-results" role="listbox" aria-label="Preconstructed decks">{decks.filter(d=>(kind==='all'||d.kind===kind)&&`${d.name} ${d.commander}`.toLowerCase().includes(search.toLowerCase())).map(d=><button role="option" aria-selected={value===d.id} key={d.id} onClick={()=>onChange(d.id)}><CardArt card={{id:-1,name:d.commander}}/><span><b>{d.name}</b><small>{d.commander}</small><small>{d.ai?.percent}% AI card coverage</small></span>{value===d.id&&<Check size={16}/>}</button>)}</div></section><section className="deck-detail">{deck?<><div className="deck-summary"><CardArt card={{id:-1,name:deck.commander}}/><div><h3>{deck.name}</h3><p>{deck.commander}</p><span>Commander · 100 cards · {deck.kind==='adapted'?'AI adaptation':'Original precon'}</span><AiCoverage value={deck.ai}/>{deck.source?.startsWith('https://')&&<a className="deck-source" href={deck.source} target="_blank" rel="noreferrer">Official Wizards decklist ↗</a>}</div></div>{!!deck.changes?.length&&<details className="deck-changes"><summary>{deck.changes.length} substitutions for AI compatibility</summary><p>The original remains available separately.</p><ul>{deck.changes.map(c=><li key={c.from}>{c.from} → {c.to}</li>)}</ul></details>}<div className="deck-card-list"><h4>Main deck · {deck.cards?.reduce((n,c)=>n+c.count,0)??99} cards</h4>{deck.cards?.map(c=><div key={c.name}><b>{c.count}</b><span>{c.name}<small>{c.type}</small></span><small>{c.mana}</small></div>)}</div></>:<p>Choose a deck to see its commander and card list.</p>}</section></div>;
}
