import {Layers3} from 'lucide-react';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import {Card,Game} from '@/lib/table';
import DecisionPanel from './decision-panel';

export default function PriorityDock({game,busy,canAct,noInteraction=false,onNoInteractionChange,ownTurn=false,onAction,onInspect,onStack}:{game:Game;noInteraction?:boolean;onNoInteractionChange?:(value:boolean)=>void;busy:boolean;canAct:boolean;ownTurn?:boolean;onAction:(body:Record<string,unknown>)=>void;onInspect:(card:Card)=>void;onStack:()=>void}){
 const [viewField,setViewField]=useState(false);
 useEffect(()=>setViewField(false),[game.confirmation,game.message,game.turn]);
 const [endTurn,setEndTurn]=useState<{version:number;turn:number}|null>(null);
 const [skipTargets,setSkipTargets]=useState<{version:number;action:string}|null>(null);
 useEffect(()=>setSkipTargets(null),[game.controlVersion]);
 const confirmAction=(action:string)=>{if(game.targeting?.min===0&&game.targeting.selected===0)setSkipTargets({version:game.controlVersion,action});else onAction({action});};
 useEffect(()=>{setEndTurn(null)},[game.controlVersion,game.turn,ownTurn]);
 const cancel=()=>{if(ownTurn&&game.cancelEndsTurn)setEndTurn({version:game.controlVersion,turn:game.turn});else confirmAction('cancel');};
 const active=!!game.decision||game.ok.enabled||game.cancel.enabled;
 const targetOption=(id:number)=>game.decision?.kind==='stack'?game.decision.options.find(o=>o.stackId===id):undefined;
 const interactionToggle=<button className={`no-interaction ${noInteraction?'enabled':''}`} role="switch" aria-checked={noInteraction} onClick={()=>onNoInteractionChange?.(!noInteraction)} title="Automatically pass your priority during AI turns. Automatically switches off when a human turn begins. Required choices still wait for you.">No interaction <span>{noInteraction?game.canAutoPass?'Passing AI turn…':'On · waiting':'Off'}</span></button>;
 return <section className={`priority-dock ${active?'needs-action':''} ${ownTurn?'own-turn':''}`} aria-label="Priority and choices">

  {game.confirmation&&!game.decision&&<><Dialog open={!viewField} onOpenChange={open=>!open&&setViewField(true)}><DialogContent><DialogTitle>{game.ok.label==='Top'&&game.cancel.label==='Bottom'?'Scry — choose top or bottom':'Ability choice'}</DialogTitle><DialogDescription>{game.message}</DialogDescription>{game.promptCard&&<button onClick={()=>onInspect(game.promptCard!)}>Inspect {game.promptCard.name}</button>}<div className="prompt-buttons"><button onClick={()=>setViewField(true)}>View battlefield</button><button disabled={!canAct||!game.ok.enabled} onClick={()=>onAction({action:'ok'})}>{game.ok.label}</button><button disabled={!canAct||!game.cancel.enabled} onClick={()=>onAction({action:'cancel'})}>{game.cancel.label}</button></div></DialogContent></Dialog>{viewField&&<button onClick={()=>setViewField(false)}>Return to choice</button>}</>}
  <Dialog open={!!skipTargets} onOpenChange={open=>!open&&setSkipTargets(null)}><DialogContent><DialogTitle>Continue without any targets?</DialogTitle><DialogDescription>{game.targeting?.source?.name??'This ability'} will not affect any targets. You can select highlighted cards on the battlefield first.</DialogDescription><div className="prompt-buttons"><button autoFocus onClick={()=>setSkipTargets(null)}>Choose targets</button><button disabled={busy||!canAct||skipTargets?.version!==game.controlVersion} onClick={()=>{if(skipTargets)onAction({action:skipTargets.action});setSkipTargets(null);}}>Continue without targets</button></div></DialogContent></Dialog>
  {game.targeting&&<div className="targeting-guide" role="status"><strong>Choose targets · {game.targeting.source?.name??'Ability'}</strong><span>{game.targeting.selected} selected · choose {game.targeting.min}–{game.targeting.max}. Click highlighted cards, then confirm.</span>{game.targeting.source&&<button onClick={()=>onInspect(game.targeting!.source!)}>Inspect source</button>}</div>}
  <Dialog open={!!endTurn} onOpenChange={open=>!open&&setEndTurn(null)}><DialogContent><DialogTitle>End your turn?</DialogTitle><DialogDescription>You will pass for the rest of this turn. Finish any plays you want to make first.</DialogDescription><div className="prompt-buttons"><button autoFocus onClick={()=>setEndTurn(null)}>Keep playing</button><button className="primary" disabled={busy||!canAct||endTurn?.version!==game.controlVersion||endTurn?.turn!==game.turn||!ownTurn||!game.cancel.enabled} onClick={()=>{setEndTurn(null);onAction({action:'cancel'});}}>End my turn</button></div></DialogContent></Dialog>
  {game.stack?.length>0&&<div className="stack-strip"><button className="stack-label" onClick={onStack}><Layers3 size={14}/>Stack · {game.stack.length}</button>{game.stack.map((item,i)=><button key={item.id} data-stack-id={item.id} className={`stack-chip ${targetOption(item.id)?'stack-selectable':''}`} disabled={busy} title={`${targetOption(item.id)?'Choose as target: ':''}${item.text}${item.targets?.length?' → '+item.targets.map(t=>t.name).join(', '):''}`} onClick={()=>{const option=targetOption(item.id);if(option&&game.decision)onAction({action:'answer',decisionId:game.decision.id,selected:[option.id]});else onInspect(item.card)}}><span>{i===0?'TOP':i+1}</span>{item.card.name||'Ability'}{targetOption(item.id)?<small>Choose as target</small>:item.targets?.length?<small>→ {item.targets.map(t=>t.name).join(', ')}</small>:null}</button>)}</div>}
  {game.decision&&interactionToggle}
  {game.decision&&(game.decision.presentation==='ability'||game.decision.presentation==='library'||game.decision.options.length>6)?<p className="library-pending">Your choice is pending. Return to the choice window to finish.</p>:game.decision?<DecisionPanel key={game.decision.id} decision={game.decision} busy={busy} onAnswer={body=>onAction({action:'answer',...body})} onInspect={onInspect}/>:<div className="priority-line"><div><span className="eyebrow">{active?'YOUR PRIORITY / ACTION':'WAITING FOR THE TABLE'}</span>{!game.targeting&&game.promptCard&&<button className="prompt-source" onClick={()=>onInspect(game.promptCard!)}>Ability / action: {game.promptCard.name} · inspect</button>}{!game.targeting&&<p aria-live="polite">{game.message||'Waiting for Forge…'}</p>}</div><div className="priority-controls">{interactionToggle}<div className="prompt-buttons"><button className="primary" disabled={!canAct||!game.ok.enabled} onClick={()=>confirmAction('ok')}>{game.ok.label||'Confirm'}</button><button disabled={!canAct||!game.cancel.enabled} onClick={cancel}>{game.cancel.label||'Cancel'}</button></div></div></div>}
 </section>;
}
