/* Compiled UI regression with synthetic API state; requires Playwright + Edge.
 * PLAYWRIGHT_MODULE may point to an installed Playwright package. GPL-3.0-or-later. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../web');
const server=http.createServer((req,res)=>{
 const file=path.join(root,req.url==='/'?'index.html':req.url.split('?')[0]);
 if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}
 fs.readFile(file,(error,data)=>{if(error){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(data);});
});
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const origin=`http://127.0.0.1:${server.address().port}`;
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 try{
 const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[],actions=[];
 page.on('pageerror',e=>errors.push(e.message));
 const card=(id,name,seat)=>({id,name,creature:true,power:3,toughness:3,type:'Creature',zone:'Battlefield',controllerSeat:seat});
 const attacker=card(11,'Rafiq of the Many',0),blocker=card(12,'Grizzly Bears',1);
 const game={controlVersion:1,cancelEndsTurn:true,message:'Priority: Alice',ok:{label:'OK',enabled:true},cancel:{label:'End Turn',enabled:true},turn:5,round:2,phase:'MAIN1',activeSeat:0,over:false,winner:'',winnerSeat:-1,stack:[],log:[],combat:[],players:[0,1,2,3].map(i=>({id:i,seat:i,name:['Alice','Bob','Carol','Dan'][i],life:40,lost:false,mana:[],counters:{},commanders:[],zones:Object.fromEntries(['Battlefield','Hand','Library','Graveyard','Exile','Command'].map(z=>[z,{count:z==='Battlefield'&&i<2?1:0,cards:z==='Battlefield'?(i===0?[attacker]:i===1?[blocker]:[]):[]}]))}))};
 const room={id:'visual',name:'UI preview',status:'playing',mySeat:0,aiOnly:false,seats:game.players.map(p=>({name:p.name,human:true,ready:true,connected:true,deck:'Test',commander:'Rafiq'})),game,chat:[]};
 const original={id:'Test',name:'Test',commander:'Rafiq',kind:'original',ai:{percent:99,total:100,flagged:1,warnings:[{name:'Simic Signet',count:1,commander:false}]},changes:[]};
 const adapted={...original,id:'Test — AI adapted',name:'Test — AI adapted',kind:'adapted',ai:{percent:100,total:100,flagged:0,warnings:[]},changes:[{from:'Simic Signet',to:'Talisman of Curiosity',count:1}]};
 for(const seat of room.seats)seat.ai=original.ai;
 await page.route('**/api/**',route=>{
  const request=route.request();
  if(request.url().endsWith('/action')){actions.push(request.postDataJSON());return route.fulfill({json:{ok:true}});}
  if(request.url().endsWith('/restart')){actions.push({action:'restart'});room.status='lobby';delete room.game;return route.fulfill({json:room});}
  return route.fulfill({json:request.url().endsWith('/health')?{ready:true,engine:'Forge',decks:[original,adapted]}:room});
 });
 await page.route('https://**/*',route=>route.abort());
 await page.addInitScript(origin=>sessionStorage.setItem('commander-table-session-v1',JSON.stringify({server:origin,room:'visual',token:'visual-only',seat:0})),origin);
 await page.goto(origin);
 await page.waitForSelector('.priority-dock.own-turn');
 const commandBox=await page.locator('.seat-0 .command-zone').boundingBox(),handBox=await page.locator('.seat-0 .hand-count').boundingBox();
 assert.ok(commandBox.x+commandBox.width<handBox.x,'Command must stay to the left of hand and the other zones');
 assert.ok((await page.locator('.hand-dock').boundingBox()).height<=140,'Unused hand height was not returned to the battlefield');
 await page.getByRole('button',{name:'End Turn',exact:true}).click();
 await page.getByRole('dialog').waitFor();assert.equal(actions.length,0);
 await page.getByRole('button',{name:'Keep playing',exact:true}).click();assert.equal(actions.length,0);
 await page.getByRole('button',{name:'End Turn',exact:true}).click();
 await page.getByRole('button',{name:'End my turn',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('[role="dialog"]'));
 assert.equal(actions.length,1);assert.equal(actions[0].action,'cancel');
 await page.getByRole('button',{name:'End Turn',exact:true}).click();
 game.controlVersion++;
 await page.waitForFunction(()=>!document.querySelector('[role="dialog"]'));
 assert.equal(actions.length,1,'Stale confirmation submitted an action');
 game.activeSeat=1;game.controlVersion++;
 await page.waitForFunction(()=>!document.querySelector('.priority-dock.own-turn'));
 await page.getByRole('button',{name:'End Turn',exact:true}).click();
 await page.waitForTimeout(100);assert.equal(actions.length,2,'Opponent turn unnecessarily confirmed');

 await page.locator('[data-card-id="11"] .card-zoom').click();
 await page.locator('.floating-card').getByRole('button',{name:'Zoom in card'}).click();
 assert.equal(await page.locator('.floating-card input[type="range"]').inputValue(),'125');
 await page.screenshot({path:path.resolve(__dirname,'../target/ui-zoom-desktop.png')});
 await page.getByRole('button',{name:'Close card',exact:true}).click();

 game.decision={id:'choice-1',kind:'order',presentation:'library',message:'Order these cards.',min:2,max:2,options:[attacker,blocker].map((c,id)=>({id,label:c.name,card:c}))};game.controlVersion++;
 await page.getByRole('dialog').waitFor();
 await page.locator('.decision-option').nth(1).click();await page.locator('.decision-option').nth(0).click();
 await page.getByRole('button',{name:'View battlefield',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('[role="dialog"]'));
 assert.equal(await page.getByRole('dialog').count(),0);
 await page.getByRole('button',{name:'Return to choice · 2 selected',exact:true}).click();
 assert.equal(await page.locator('.decision-option.chosen').count(),2);
 assert.equal(await page.locator('.chosen-order>div').first().locator('span').textContent(),'1. Grizzly Bears');
 await page.getByRole('button',{name:'Confirm selection',exact:true}).click();
 await page.waitForTimeout(100);
 assert.deepEqual(actions.at(-1).selected,[1,0]);
 game.decision=undefined;game.controlVersion++;
 await page.waitForFunction(()=>!document.querySelector('[role="dialog"]'));
 // Browsing a zone uses the same zoom/minimize controls, without losing its context.
 game.players[0].zones.Graveyard={count:1,cards:[attacker]};game.controlVersion++;
 await page.waitForFunction(()=>document.querySelector('.seat-0 [data-zone="Graveyard"] b')?.textContent==='1');
 await page.locator('.seat-0 [data-zone="Graveyard"]').click();
 await page.getByRole('dialog').getByRole('button',{name:'Zoom in card'}).click();
 assert.equal(await page.getByRole('dialog').locator('input[type="range"]').inputValue(),'125');
 await page.getByRole('button',{name:'View battlefield',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('[role="dialog"]'));
 await page.getByRole('button',{name:'Return to Graveyard · Alice',exact:true}).click();
 await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('[role="dialog"]'));
 game.players[0].monarch=true;game.players[0].commanders=[{name:'Rafiq of the Many',from:1,damage:12,casts:1}];game.controlVersion++;
 await page.waitForSelector('.seat-0 .monarch-badge');
 assert.equal(await page.locator('.seat-0 .commander-damage b').textContent(),'12');
 await page.locator('.seat-0 .commander-damage').click();
 assert.equal(await page.getByRole('dialog').locator('.damage-detail strong').textContent(),'12 / 21');
 await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();
 assert.equal(await page.locator('.seat-0 .zones .hand-count').count(),1);
 assert.equal(await page.locator('.seat-0 .zones .command-zone').count(),1);
 game.players[0].monarch=false;game.players[1].monarch=true;game.controlVersion++;
 await page.waitForSelector('.seat-1 .monarch-badge');
 assert.equal(await page.locator('.seat-0 .monarch-badge').count(),0);
 room.aiOnly=true;game.players[1].lastAction={id:700,stackId:100,kind:'cast',card:blocker,text:'Grizzly Bears enters the battle!'};game.controlVersion++;
 await page.waitForSelector('.seat-1 .spectator-announcement');
 await page.waitForTimeout(350);
 await page.screenshot({path:path.resolve(__dirname,'../target/ui-spectator-desktop.png')});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:path.resolve(__dirname,'../target/ui-spectator-mobile.png')});
 assert.equal(await page.locator('.seat-0 .hand-count').isVisible(),true);
 await page.setViewportSize({width:1440,height:900});
 delete game.players[1].lastAction;game.controlVersion++;
 await page.waitForTimeout(2000);
 assert.equal(await page.locator('.seat-1 .spectator-announcement').count(),1,'Announcement disappeared with the resolved stack');
 await page.waitForSelector('.spectator-announcement',{state:'detached'});
 room.aiOnly=false;
 game.players[1].lost=true;game.controlVersion++;
 await page.waitForSelector('.seat-1 .player-result.defeated');
 game.over=true;game.winner='Alice';game.winnerSeat=0;room.status='finished';game.controlVersion++;
 await page.waitForSelector('.seat-0 .player-result.victorious');
 assert.equal(await page.locator('.match-result strong').textContent(),'Alice wins!');
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:path.resolve(__dirname,'../target/ui-outcome-mobile.png')});
 await page.getByRole('button',{name:'Restart',exact:true}).click();
 await page.getByRole('button',{name:'Keep watching or playing',exact:true}).click();
 assert.ok(!actions.some(a=>a.action==='restart'));
 await page.getByRole('button',{name:'Restart',exact:true}).click();
 await page.getByRole('button',{name:'Return to deck selection',exact:true}).click();
 await page.waitForSelector('.lobby-panel');
 assert.equal(actions.filter(a=>a.action==='restart').length,1);
 assert.equal(await page.getByText('Host key',{exact:true}).count(),0);
 await page.setViewportSize({width:1440,height:900});
 await page.locator('.lobby-panel').getByRole('button',{name:'Change my deck',exact:true}).click();
 await page.getByRole('dialog').locator('.ai-coverage').click();
 await page.getByText('1 × Simic Signet',{exact:true}).waitFor();
 assert.ok((await page.getByRole('dialog').last().textContent()).includes('not how often'));
 await page.getByRole('dialog').last().getByRole('button',{name:'Close',exact:true}).click();
 await page.getByRole('combobox').click();
 await page.getByRole('option',{name:'Test — AI adapted · 100% AI coverage',exact:true}).click();
 await page.getByText('1 substitutions for AI compatibility',{exact:true}).click();
 await page.getByText('Simic Signet → Talisman of Curiosity',{exact:true}).waitFor();
 await page.screenshot({path:path.resolve(__dirname,'../target/ui-ai-catalog.png')});
 await page.getByRole('dialog').locator('.ai-coverage').click();
 await page.getByText('No cards in this deck carry the current Forge AI warning.',{exact:true}).waitFor();
 assert.deepEqual(errors,[]);
 console.log('PASS: end-turn, zoom, minimized choices, monarch transfer, commander damage details, mobile zone indicators, retained spectator balloons, restart confirmation, defeat and victory; no browser errors');
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(()=>server.close());
